export const products = {
  tagheuer: [
    { name: "Carrera Chronograph", type:"Tag Heuer",  price: "₱ 5,900", img: "./img/F-Product/1.png" },
    { name: "Formula 1 Chronograph", type:"Tag Heuer", price: "₱ 2,600", img: "./img/F-Product/2.png" },
    { name: "Monaco Chronograph", type:"Tag Heuer", price: "₱ 11,500", img: "./img/Product/Taghuer/3.png" },
    { name: "Carrera X Porche Chronograph", type:"Tag Heuer", price: "₱ 7,250", img: "./img/Product/Taghuer/4.png" },
    { name: "Aquaracer Chronograph", type:"Tag Heuer", price: "₱ 3,100", img: "./img/Product/Taghuer/5.png" },
    { name: "F1 Chronograph x Redbull Racing", type:"Tag Heuer", price: "₱ 2,250", img: "./img/Product/Taghuer/6.png" },
    { name: "Carrera Day Date", type:"Tag Heuer", price: "₱ 4,500", img: "./img/Product/Taghuer/7.png" },
    { name: "Formula 1 Solargraph", type:"Tag Heuer", price: "₱ 2,050", img: "./img/Product/Taghuer/8.png" },
    { name: "Formula 1 Date", type:"Tag Heuer", price: "₱ 1,850", img: "./img/Product/Taghuer/9.png" },
    { name: "Chronograph Year of the Horse", type:"Tag Heuer", price: "₱ 8,150", img: "./img/Product/Taghuer/10.png" },
    { name: "Carrera Chronograph X Fragment Limited Edition", type:"Tag Heuer", price: "₱ 9,050", img: "./img/Product/Taghuer/11.png" },
    { name: "F1 Chronosprint x Porche 911 (1964)", type:"Tag Heuer", price: "₱ 23,400", img: "./img/Product/Taghuer/12.png" },
  ],

  rolex: [
    { name: "Sea Dwealer", type:"Rolex", price: "₱ 720,000", img: "/img/F-Product/6.png" },
    { name: "GMT-Master II", type:"Rolex", price: "₱ 618,516", img: "./img/Product/Rolex/2.png" },
    { name: "Daytona", type:"Rolex", price: "₱ 905,568", img: "./img/Product/Rolex/3.png" },
    { name: "Submariner", type:"Rolex", price: "₱ 454,375", img: "./img/Product/Rolex/4.png" },
    { name: "Datejust", type:"Rolex", price: "₱ 130,478", img: "./img/Product/Rolex/5.png" },
    { name: "Daydate", type:"Rolex", price: "₱ 519,933", img: "./img/Product/Rolex/6.png" },
    { name: "Oyster Perpetual", type:"Rolex", price: "₱ 94,482", img: "./img/Product/Rolex/7.png" },
    { name: "Lady Dayjust", type:"Rolex", price: "₱ 164,070", img: "./img/Product/Rolex/8.png" },
    { name: "Dayjust 41 Limited Edition", type:"Rolex", price: "₱ 950,579", img: "./img/Product/Rolex/9.png" },
  ],

  gshock: [
    { name: "GST-B600",type:"G-Shock", price: "₱ 7,500", img: "./img/F-Product/5.png" },
    { name: "GMC-B2100BT-1A",type:"G-Shock", price: "₱ 57,110", img: "./img/Product/gshock/2.png" },
    { name: "GM-S2110BP-5A", type:"G-Shock", price: "₱ 19,590", img: "./img/Product/gshock/3.png" },
    { name: "GM-2100M-1A", type:"G-Shock", price: "₱ 16,640", img: "./img/Product/gshock/4.png" },
    { name: "GM-2110D-3A1", type:"G-Shock", price: "₱ 18,480", img: "./img/Product/gshock/5.png" },
    { name: "GBM-2100CX-9A", type:"G-Shock", price: "₱ 21,070", img: "./img/Product/gshock/6.png" },
    { name: "GBM-2100A-8B", type:"G-Shock", price: "₱ 18,300", img: "./img/Product/gshock/7.png" },
    { name: "GST-B100D-1A", type:"G-Shock", price: "₱ 32,020", img: "./img/Product/gshock/8.png" },
    { name: "GST-B400BB-1A", type:"G-Shock", price: "₱ 26,060", img: "./img/Product/gshock/9.png" },
    { name: "GST-S100G-1B", type:"G-Shock", price: "₱ 19,360", img: "./img/Product/gshock/10.png" },
    { name: "GM-5600UB-1", type:"G-Shock", price: "₱ 14,600", img: "./img/Product/gshock/11.png" },
    { name: "GM-110BB-1A", type:"G-Shock", price: "₱ 17,470", img: "./img/Product/gshock/12.png" },
    { name: "GM-5600U-1", type:"G-Shock", price: "₱ 11,830", img: "./img/Product/gshock/13.png" },
    { name: "GM-2100CB-3A", type:"G-Shock", price: "₱ 17,560", img: "./img/Product/gshock/14.png" },
    { name: "Cassio Edition", type:"G-Shock", price: "₱ 8,034", img: "./img/Product/gshock/15.png" },
    { name: "Tough Solar", type:"G-Shock", price: "₱ 2,377", img: "./img/Product/gshock/16.png" },
    { name: "DW9052-1C Digital", type:"G-Shock", price: "₱ 4,219", img: "./img/Product/gshock/17.png" },
    { name: "Steel Solar GSTS100G-1A", type:"G-Shock", price: "₱ 15, 918", img: "./img/Product/gshock/18.png" },
  ],

  fossil: [
    { name: "Machine Quartz", type:"Fossil", price: "₱ 12,999", img: "./img/F-Product/3.png" },
    { name: "Raquel Three-Hand Date", type:"Fossil",  price: "₱ 10,125", img: "./img/F-Product/4.png" },
    { name: "Men's Townsman", type:"Fossil", price: "₱ 13,359", img: "./img/Product/Fossil/3.png" },
    { name: "Men's FS4736", type:"Fossil", price: "₱ 9,165", img: "./img/Product/Fossil/4.png" },
    { name: "Flynn Chronograph", type:"Fossil", price: "₱ 8,914", img: "./img/Product/Fossil/5.png" },
    { name: "Neutra Chronograph", type:"Fossil", price: "₱ 21,988", img: "./img/Product/Fossil/6.png" },
    { name: "Fenmore", type:"Fossil", price: "₱ 9,805", img: "./img/Product/Fossil/7.png" },
    { name: "FS6121", type:"Fossil", price: "₱ 8,571", img: "./img/Product/Fossil/8.png" },
    { name: "FS4931", type:"Fossil", price: "₱ 9,096", img: "./img/Product/Fossil/9.png" },
    { name: "BLUE-GMT", type:"Fossil", price: "₱ 8,571", img: "./img/Product/Fossil/10.png" },
    { name: "Men's Minimalist", type:"Fossil", price: "₱ 11,300", img: "./img/Product/Fossil/11.png" },
    { name: "Pilot", type:"Fossil", price: "₱ 10,348", img: "./img/Product/Fossil/12.png" },
    { name: "JR1354", type:"Fossil", price: "₱ 14,243", img: "./img/Product/Fossil/13.png" },
    { name: "Grant Me3099", type:"Fossil", price: "₱ 15,157", img: "./img/Product/Fossil/14.png" },
    { name: "Cuff", type:"Fossil", price: "₱ 7,072", img: "./img/Product/Fossil/15.png" },
  ],

  tissot: [
   { name: "PRX-Powermatic", type:"Tissot", price: "₱ 42,466 ", img: "./img/Product/Tissot/1.png" },
   { name: "Gentle Powermatic", type:"Tissot", price: "₱ 56,458", img: "./img/Product/Tissot/2.png" },
   { name: "T-Classic Le Locle", type:"Tissot", price: "₱ 43,700", img: "./img/Product/Tissot/3.png" },
   { name: "Women's PRX-Powermatic", type:"Tissot", price: "₱ 20,354", img: "./img/Product/Tissot/4.png" },
   { name: "Ballad", type:"Tissot", price: "₱ 22,600", img: "./img/Product/Tissot/5.png" },
   { name: "PRC-100 Solar", type:"Tissot", price: "₱ 31,100 ", img: "./img/Product/Tissot/6.png" },
   { name: "Women's Tradition Quartz XL", type:"Tissot", price: "₱ 17,500", img: "./img/Product/Tissot/7.png" },
   { name: "PR-100 Chronograph", type:"Tissot", price: "₱ 36,073", img: "./img/Product/Tissot/8.png" },
   { name: "PR-516 Chrono Steel Watch", type:"Tissot", price: "₱ 29,900", img: "./img/Product/Tissot/9.png" },
   { name: "Seastar 1000", type:"Tissot", price: "₱ 61,698", img: "./img/Product/Tissot/10.png" },
   { name: "Super Sport Chrono", type:"Tissot", price: "₱ 29,596", img: "./img/Product/Tissot/11.png" },
   { name: "Women's Lovely Square", type:"Tissot", price: "₱ 20,400 ", img: "./img/Product/Tissot/12.png" },
  ]
};

products.all = Object.values(products).flat();